### ISSUE TITLE
Zero is wrong

### ISSUE THREAD

**Issue by llemtt** [mhoseini967/AdvancedSevenSegment#1]
Hi,

case 0 is wrong inside setNumber(int number), it displays an 'A' !

it should be:

print(1, 1, 1, 1, 1, 1, 0);

instead of:

print(1, 1, 1, 0, 1, 1, 1);

**Comment by mhoseini967** [comment]
fixed it in 151430d14b6d597596ff9f6a40af9ce38cb359d8
